services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    volumes:
      - ./db.db:/app/prisma/db.db 
      - ./uploads:/app/uploads 
    restart: unless-stopped
    env_file:
      - .env